### ISSUE TITLE
SNOW-536479: PHP 8.1 Support

### ISSUE THREAD

**Issue by salvor-hardin** [snowflakedb/pdo_snowflake#272]
Please add support for PHP 8.1 as it has been released in late November
https://www.php.net/archive/2021.php#2021-11-25-1

**Comment by salvor-hardin** [comment]
Also, this needs to be thread safe or what's the point on a NTS extension to connect to external databases?

Can't make it work with PHP 8.0.15 either

PHP Warning:  PHP Startup: pdo_snowflake: Unable to initialize module
Module compiled with build ID=API20200930,NTS
PHP    compiled with build ID=API20200930,TS

**Comment by plsoucy-tapclicks** [comment]
+1 on this - PHP 8.1 was released two months ago and we'll need to support it soon.

When using the latest code from this repository, I can build just fine using PHP 8.0.3 (older version we had on our test server).

However, on the latest PHP 8.1 (8.1.2), I get this when running ./scripts/build_pdo_snowflake.sh:
```
/home/programs/snowflake-pdo2/snowflake_driver.c:434:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_closer,
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:434:5: note: (near initialization for ‘snowflake_methods.closer’)
/home/programs/snowflake-pdo2/snowflake_driver.c:435:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_preparer,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:435:5: note: (near initialization for ‘snowflake_methods.preparer’)
/home/programs/snowflake-pdo2/snowflake_driver.c:436:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_doer,
     ^~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:436:5: note: (near initialization for ‘snowflake_methods.doer’)
/home/programs/snowflake-pdo2/snowflake_driver.c:437:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_quoter,
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:437:5: note: (near initialization for ‘snowflake_methods.quoter’)
/home/programs/snowflake-pdo2/snowflake_driver.c:438:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_begin,
     ^~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:438:5: note: (near initialization for ‘snowflake_methods.begin’)
/home/programs/snowflake-pdo2/snowflake_driver.c:439:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_commit,
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:439:5: note: (near initialization for ‘snowflake_methods.commit’)
/home/programs/snowflake-pdo2/snowflake_driver.c:440:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     snowflake_handle_rollback,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:440:5: note: (near initialization for ‘snowflake_methods.rollback’)
/home/programs/snowflake-pdo2/snowflake_driver.c:441:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     pdo_snowflake_set_attribute,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:441:5: note: (near initialization for ‘snowflake_methods.set_attribute’)
/home/programs/snowflake-pdo2/snowflake_driver.c:442:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     pdo_snowflake_last_insert_id,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:442:5: note: (near initialization for ‘snowflake_methods.last_id’)
/home/programs/snowflake-pdo2/snowflake_driver.c:443:5: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     pdo_snowflake_fetch_error_func,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/programs/snowflake-pdo2/snowflake_driver.c:443:5: note: (near initialization for ‘snowflake_methods.fetch_err’)
```

Can you please advise on potential fixes/timelines? Thanks.

**Comment by bnd-php** [comment]
It has been a while since the issue was opened. 
Can you please provide a timeline? Thank you.

**Comment by salvor-hardin** [comment]
PHP 8.1.3 released... still no PDO driver on sight for this :(
https://www.php.net/supported-versions.php

iodbc connections are painful...

**Comment by plsoucy-tapclicks** [comment]
Any update on this? This issue has been open for more than 3 weeks and we still haven't heard back form the Snowflake team.

**Comment by sfc-gh-hkapre** [comment]
Sorry for the delay. We are evaluating the effort and will come back with more details shortly.

**Comment by sfc-gh-hkapre** [comment]
Targeting the update in early Q2.

**Comment by sfc-gh-ngoodman** [comment]
This shipped with Version 1.2.1 (Mar 16, 2022)
 https://community.snowflake.com/s/article/PHP-PDO-Driver-for-Snowflake 

Issue can be closed!
